/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.message.boards.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.message.boards.model.MBSuspiciousActivityType;
import com.liferay.message.boards.service.MBSuspiciousActivityTypeLocalService;
import com.liferay.message.boards.service.MBSuspiciousActivityTypeLocalServiceUtil;
import com.liferay.message.boards.service.persistence.MBSuspiciousActivityTypePersistence;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the message boards suspicious activity type local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.message.boards.service.impl.MBSuspiciousActivityTypeLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.message.boards.service.impl.MBSuspiciousActivityTypeLocalServiceImpl
 * @generated
 */
public abstract class MBSuspiciousActivityTypeLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   MBSuspiciousActivityTypeLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>MBSuspiciousActivityTypeLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>MBSuspiciousActivityTypeLocalServiceUtil</code>.
	 */

	/**
	 * Adds the message boards suspicious activity type to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MBSuspiciousActivityTypeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param mbSuspiciousActivityType the message boards suspicious activity type
	 * @return the message boards suspicious activity type that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MBSuspiciousActivityType addMBSuspiciousActivityType(
		MBSuspiciousActivityType mbSuspiciousActivityType) {

		mbSuspiciousActivityType.setNew(true);

		return mbSuspiciousActivityTypePersistence.update(
			mbSuspiciousActivityType);
	}

	/**
	 * Creates a new message boards suspicious activity type with the primary key. Does not add the message boards suspicious activity type to the database.
	 *
	 * @param suspiciousActivityTypeId the primary key for the new message boards suspicious activity type
	 * @return the new message boards suspicious activity type
	 */
	@Override
	@Transactional(enabled = false)
	public MBSuspiciousActivityType createMBSuspiciousActivityType(
		long suspiciousActivityTypeId) {

		return mbSuspiciousActivityTypePersistence.create(
			suspiciousActivityTypeId);
	}

	/**
	 * Deletes the message boards suspicious activity type with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MBSuspiciousActivityTypeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param suspiciousActivityTypeId the primary key of the message boards suspicious activity type
	 * @return the message boards suspicious activity type that was removed
	 * @throws PortalException if a message boards suspicious activity type with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MBSuspiciousActivityType deleteMBSuspiciousActivityType(
			long suspiciousActivityTypeId)
		throws PortalException {

		return mbSuspiciousActivityTypePersistence.remove(
			suspiciousActivityTypeId);
	}

	/**
	 * Deletes the message boards suspicious activity type from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MBSuspiciousActivityTypeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param mbSuspiciousActivityType the message boards suspicious activity type
	 * @return the message boards suspicious activity type that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MBSuspiciousActivityType deleteMBSuspiciousActivityType(
		MBSuspiciousActivityType mbSuspiciousActivityType) {

		return mbSuspiciousActivityTypePersistence.remove(
			mbSuspiciousActivityType);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return mbSuspiciousActivityTypePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			MBSuspiciousActivityType.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return mbSuspiciousActivityTypePersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.message.boards.model.impl.MBSuspiciousActivityTypeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return mbSuspiciousActivityTypePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.message.boards.model.impl.MBSuspiciousActivityTypeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return mbSuspiciousActivityTypePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return mbSuspiciousActivityTypePersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return mbSuspiciousActivityTypePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public MBSuspiciousActivityType fetchMBSuspiciousActivityType(
		long suspiciousActivityTypeId) {

		return mbSuspiciousActivityTypePersistence.fetchByPrimaryKey(
			suspiciousActivityTypeId);
	}

	/**
	 * Returns the message boards suspicious activity type matching the UUID and group.
	 *
	 * @param uuid the message boards suspicious activity type's UUID
	 * @param groupId the primary key of the group
	 * @return the matching message boards suspicious activity type, or <code>null</code> if a matching message boards suspicious activity type could not be found
	 */
	@Override
	public MBSuspiciousActivityType
		fetchMBSuspiciousActivityTypeByUuidAndGroupId(
			String uuid, long groupId) {

		return mbSuspiciousActivityTypePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the message boards suspicious activity type with the primary key.
	 *
	 * @param suspiciousActivityTypeId the primary key of the message boards suspicious activity type
	 * @return the message boards suspicious activity type
	 * @throws PortalException if a message boards suspicious activity type with the primary key could not be found
	 */
	@Override
	public MBSuspiciousActivityType getMBSuspiciousActivityType(
			long suspiciousActivityTypeId)
		throws PortalException {

		return mbSuspiciousActivityTypePersistence.findByPrimaryKey(
			suspiciousActivityTypeId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			mbSuspiciousActivityTypeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MBSuspiciousActivityType.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"suspiciousActivityTypeId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			mbSuspiciousActivityTypeLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			MBSuspiciousActivityType.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"suspiciousActivityTypeId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			mbSuspiciousActivityTypeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MBSuspiciousActivityType.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"suspiciousActivityTypeId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<MBSuspiciousActivityType>() {

				@Override
				public void performAction(
						MBSuspiciousActivityType mbSuspiciousActivityType)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, mbSuspiciousActivityType);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					MBSuspiciousActivityType.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return mbSuspiciousActivityTypePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return mbSuspiciousActivityTypeLocalService.
			deleteMBSuspiciousActivityType(
				(MBSuspiciousActivityType)persistedModel);
	}

	@Override
	public BasePersistence<MBSuspiciousActivityType> getBasePersistence() {
		return mbSuspiciousActivityTypePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return mbSuspiciousActivityTypePersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the message boards suspicious activity types matching the UUID and company.
	 *
	 * @param uuid the UUID of the message boards suspicious activity types
	 * @param companyId the primary key of the company
	 * @return the matching message boards suspicious activity types, or an empty list if no matches were found
	 */
	@Override
	public List<MBSuspiciousActivityType>
		getMBSuspiciousActivityTypesByUuidAndCompanyId(
			String uuid, long companyId) {

		return mbSuspiciousActivityTypePersistence.findByUuid_C(
			uuid, companyId);
	}

	/**
	 * Returns a range of message boards suspicious activity types matching the UUID and company.
	 *
	 * @param uuid the UUID of the message boards suspicious activity types
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of message boards suspicious activity types
	 * @param end the upper bound of the range of message boards suspicious activity types (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching message boards suspicious activity types, or an empty list if no matches were found
	 */
	@Override
	public List<MBSuspiciousActivityType>
		getMBSuspiciousActivityTypesByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<MBSuspiciousActivityType> orderByComparator) {

		return mbSuspiciousActivityTypePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the message boards suspicious activity type matching the UUID and group.
	 *
	 * @param uuid the message boards suspicious activity type's UUID
	 * @param groupId the primary key of the group
	 * @return the matching message boards suspicious activity type
	 * @throws PortalException if a matching message boards suspicious activity type could not be found
	 */
	@Override
	public MBSuspiciousActivityType getMBSuspiciousActivityTypeByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return mbSuspiciousActivityTypePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the message boards suspicious activity types.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.message.boards.model.impl.MBSuspiciousActivityTypeModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of message boards suspicious activity types
	 * @param end the upper bound of the range of message boards suspicious activity types (not inclusive)
	 * @return the range of message boards suspicious activity types
	 */
	@Override
	public List<MBSuspiciousActivityType> getMBSuspiciousActivityTypes(
		int start, int end) {

		return mbSuspiciousActivityTypePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of message boards suspicious activity types.
	 *
	 * @return the number of message boards suspicious activity types
	 */
	@Override
	public int getMBSuspiciousActivityTypesCount() {
		return mbSuspiciousActivityTypePersistence.countAll();
	}

	/**
	 * Updates the message boards suspicious activity type in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MBSuspiciousActivityTypeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param mbSuspiciousActivityType the message boards suspicious activity type
	 * @return the message boards suspicious activity type that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MBSuspiciousActivityType updateMBSuspiciousActivityType(
		MBSuspiciousActivityType mbSuspiciousActivityType) {

		return mbSuspiciousActivityTypePersistence.update(
			mbSuspiciousActivityType);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			MBSuspiciousActivityTypeLocalService.class,
			IdentifiableOSGiService.class, CTService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		mbSuspiciousActivityTypeLocalService =
			(MBSuspiciousActivityTypeLocalService)aopProxy;

		_setLocalServiceUtilService(mbSuspiciousActivityTypeLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MBSuspiciousActivityTypeLocalService.class.getName();
	}

	@Override
	public CTPersistence<MBSuspiciousActivityType> getCTPersistence() {
		return mbSuspiciousActivityTypePersistence;
	}

	@Override
	public Class<MBSuspiciousActivityType> getModelClass() {
		return MBSuspiciousActivityType.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<MBSuspiciousActivityType>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(mbSuspiciousActivityTypePersistence);
	}

	protected String getModelClassName() {
		return MBSuspiciousActivityType.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				mbSuspiciousActivityTypePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		MBSuspiciousActivityTypeLocalService
			mbSuspiciousActivityTypeLocalService) {

		try {
			Field field =
				MBSuspiciousActivityTypeLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, mbSuspiciousActivityTypeLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected MBSuspiciousActivityTypeLocalService
		mbSuspiciousActivityTypeLocalService;

	@Reference
	protected MBSuspiciousActivityTypePersistence
		mbSuspiciousActivityTypePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}