/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.message.boards.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MBSuspiciousActivityType service. Represents a row in the &quot;MBSuspiciousActivityType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.message.boards.model.impl.MBSuspiciousActivityTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.message.boards.model.impl.MBSuspiciousActivityTypeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MBSuspiciousActivityType
 * @generated
 */
@ProviderType
public interface MBSuspiciousActivityTypeModel
	extends BaseModel<MBSuspiciousActivityType>, ContainerModel,
			CTModel<MBSuspiciousActivityType>, GroupedModel, MVCCModel,
			ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a message boards suspicious activity type model instance should use the {@link MBSuspiciousActivityType} interface instead.
	 */

	/**
	 * Returns the primary key of this message boards suspicious activity type.
	 *
	 * @return the primary key of this message boards suspicious activity type
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this message boards suspicious activity type.
	 *
	 * @param primaryKey the primary key of this message boards suspicious activity type
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this message boards suspicious activity type.
	 *
	 * @return the mvcc version of this message boards suspicious activity type
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this message boards suspicious activity type.
	 *
	 * @param mvccVersion the mvcc version of this message boards suspicious activity type
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this message boards suspicious activity type.
	 *
	 * @return the ct collection ID of this message boards suspicious activity type
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this message boards suspicious activity type.
	 *
	 * @param ctCollectionId the ct collection ID of this message boards suspicious activity type
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the uuid of this message boards suspicious activity type.
	 *
	 * @return the uuid of this message boards suspicious activity type
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this message boards suspicious activity type.
	 *
	 * @param uuid the uuid of this message boards suspicious activity type
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the suspicious activity type ID of this message boards suspicious activity type.
	 *
	 * @return the suspicious activity type ID of this message boards suspicious activity type
	 */
	public long getSuspiciousActivityTypeId();

	/**
	 * Sets the suspicious activity type ID of this message boards suspicious activity type.
	 *
	 * @param suspiciousActivityTypeId the suspicious activity type ID of this message boards suspicious activity type
	 */
	public void setSuspiciousActivityTypeId(long suspiciousActivityTypeId);

	/**
	 * Returns the group ID of this message boards suspicious activity type.
	 *
	 * @return the group ID of this message boards suspicious activity type
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this message boards suspicious activity type.
	 *
	 * @param groupId the group ID of this message boards suspicious activity type
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this message boards suspicious activity type.
	 *
	 * @return the company ID of this message boards suspicious activity type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this message boards suspicious activity type.
	 *
	 * @param companyId the company ID of this message boards suspicious activity type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this message boards suspicious activity type.
	 *
	 * @return the user ID of this message boards suspicious activity type
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this message boards suspicious activity type.
	 *
	 * @param userId the user ID of this message boards suspicious activity type
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this message boards suspicious activity type.
	 *
	 * @return the user uuid of this message boards suspicious activity type
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this message boards suspicious activity type.
	 *
	 * @param userUuid the user uuid of this message boards suspicious activity type
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this message boards suspicious activity type.
	 *
	 * @return the user name of this message boards suspicious activity type
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this message boards suspicious activity type.
	 *
	 * @param userName the user name of this message boards suspicious activity type
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this message boards suspicious activity type.
	 *
	 * @return the create date of this message boards suspicious activity type
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this message boards suspicious activity type.
	 *
	 * @param createDate the create date of this message boards suspicious activity type
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this message boards suspicious activity type.
	 *
	 * @return the modified date of this message boards suspicious activity type
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this message boards suspicious activity type.
	 *
	 * @param modifiedDate the modified date of this message boards suspicious activity type
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the description of this message boards suspicious activity type.
	 *
	 * @return the description of this message boards suspicious activity type
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this message boards suspicious activity type.
	 *
	 * @param description the description of this message boards suspicious activity type
	 */
	public void setDescription(String description);

	/**
	 * Returns the container model ID of this message boards suspicious activity type.
	 *
	 * @return the container model ID of this message boards suspicious activity type
	 */
	@Override
	public long getContainerModelId();

	/**
	 * Sets the container model ID of this message boards suspicious activity type.
	 *
	 * @param containerModelId the container model ID of this message boards suspicious activity type
	 */
	@Override
	public void setContainerModelId(long containerModelId);

	/**
	 * Returns the container name of this message boards suspicious activity type.
	 *
	 * @return the container name of this message boards suspicious activity type
	 */
	@Override
	public String getContainerModelName();

	/**
	 * Returns the parent container model ID of this message boards suspicious activity type.
	 *
	 * @return the parent container model ID of this message boards suspicious activity type
	 */
	@Override
	public long getParentContainerModelId();

	/**
	 * Sets the parent container model ID of this message boards suspicious activity type.
	 *
	 * @param parentContainerModelId the parent container model ID of this message boards suspicious activity type
	 */
	@Override
	public void setParentContainerModelId(long parentContainerModelId);

	@Override
	public MBSuspiciousActivityType cloneWithOriginalValues();

}