/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.message.boards.uad.exporter;

import com.liferay.message.boards.model.MBSuspiciousActivityType;
import com.liferay.message.boards.service.MBSuspiciousActivityTypeLocalService;
import com.liferay.message.boards.uad.constants.MBUADConstants;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the message boards suspicious activity type UAD exporter.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link MBSuspiciousActivityTypeUADExporter}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseMBSuspiciousActivityTypeUADExporter
	extends DynamicQueryUADExporter<MBSuspiciousActivityType> {

	@Override
	public Class<MBSuspiciousActivityType> getTypeClass() {
		return MBSuspiciousActivityType.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return mbSuspiciousActivityTypeLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return MBUADConstants.USER_ID_FIELD_NAMES_MB_SUSPICIOUS_ACTIVITY_TYPE;
	}

	@Override
	protected String toXmlString(
		MBSuspiciousActivityType mbSuspiciousActivityType) {

		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.liferay.message.boards.model.MBSuspiciousActivityType");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>suspiciousActivityTypeId</column-name><column-value><![CDATA[");
		sb.append(mbSuspiciousActivityType.getSuspiciousActivityTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(mbSuspiciousActivityType.getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(mbSuspiciousActivityType.getUserName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	@Reference
	protected MBSuspiciousActivityTypeLocalService
		mbSuspiciousActivityTypeLocalService;

}