/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.message.boards.uad.anonymizer;

import com.liferay.asset.kernel.model.AssetEntry;
import com.liferay.asset.kernel.service.AssetEntryLocalService;
import com.liferay.message.boards.model.MBSuspiciousActivityType;
import com.liferay.message.boards.service.MBSuspiciousActivityTypeLocalService;
import com.liferay.message.boards.uad.constants.MBUADConstants;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the message boards suspicious activity type UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link MBSuspiciousActivityTypeUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseMBSuspiciousActivityTypeUADAnonymizer
	extends DynamicQueryUADAnonymizer<MBSuspiciousActivityType> {

	@Override
	public void autoAnonymize(
			MBSuspiciousActivityType mbSuspiciousActivityType, long userId,
			User anonymousUser)
		throws PortalException {

		if (mbSuspiciousActivityType.getUserId() == userId) {
			mbSuspiciousActivityType.setUserId(anonymousUser.getUserId());
			mbSuspiciousActivityType.setUserName(anonymousUser.getFullName());

			autoAnonymizeAssetEntry(mbSuspiciousActivityType, anonymousUser);
		}

		mbSuspiciousActivityTypeLocalService.updateMBSuspiciousActivityType(
			mbSuspiciousActivityType);
	}

	@Override
	public void delete(MBSuspiciousActivityType mbSuspiciousActivityType)
		throws PortalException {

		mbSuspiciousActivityTypeLocalService.deleteMBSuspiciousActivityType(
			mbSuspiciousActivityType);
	}

	@Override
	public Class<MBSuspiciousActivityType> getTypeClass() {
		return MBSuspiciousActivityType.class;
	}

	protected void autoAnonymizeAssetEntry(
		MBSuspiciousActivityType mbSuspiciousActivityType, User anonymousUser) {

		AssetEntry assetEntry = fetchAssetEntry(mbSuspiciousActivityType);

		if (assetEntry != null) {
			assetEntry.setUserId(anonymousUser.getUserId());
			assetEntry.setUserName(anonymousUser.getFullName());

			assetEntryLocalService.updateAssetEntry(assetEntry);
		}
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return mbSuspiciousActivityTypeLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return MBUADConstants.USER_ID_FIELD_NAMES_MB_SUSPICIOUS_ACTIVITY_TYPE;
	}

	protected AssetEntry fetchAssetEntry(
		MBSuspiciousActivityType mbSuspiciousActivityType) {

		return assetEntryLocalService.fetchEntry(
			MBSuspiciousActivityType.class.getName(),
			mbSuspiciousActivityType.getSuspiciousActivityTypeId());
	}

	@Reference
	protected AssetEntryLocalService assetEntryLocalService;

	@Reference
	protected MBSuspiciousActivityTypeLocalService
		mbSuspiciousActivityTypeLocalService;

}